### PR TITLE
separate upload test data and evaluate method

### PR DESCRIPTION
**Pull request by yuki-mt**
I added UploadEvaluationData just to upload test data. (to avoid waisting disk. ref: https://github.com/rekcurd/drucker/pull/11#discussion_r234496000 )
Instead, `EvaluateModelRequest` has `result_path`, which is path where the evaluation result is saved.

If it is approved, I will also change drucker and drucker-dashboard.

### CODE REVIEW

**Comment by keigohtr** [comment]
@yuki-mt Thank you for the improvement!
Although this PR changes `message` completely, we need to keep a backward compatibility. Could you define the new field and reserve the previous field?

`Reserved Fields` of this [link](https://developers.google.com/protocol-buffers/docs/proto3) will be helpful for you.

**Comment by yuki-mt** [comment]
@keigohtr All right.
I added `reserved` to EvaluateModelRequest, so please check it.

I also updated compile files.

**Comment by yuki-mt** [comment]
@keigohtr 
To completely keep back compatibility, I restored update of `EvaluateModel` and made some comments.

**Review by keigohtr — APPROVED** [review]
LGTM
(But DO NOT MERGE it right now)

**Pull request merged**
